# Generated by Django 5.0.4 on 2024-05-05 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoloObjectDetectionAPI', '0002_alter_detections_object_detection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='processed_images/')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_timestamp', models.DateTimeField(blank=True, null=True)),
                ('confidence_threshold', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image_file',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='status',
            field=models.CharField(choices=[('processing', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=50),
        ),
    ]
