# Generated by Django 5.0.4 on 2024-05-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YoloObjectDetectionAPI', '0003_processedimage_alter_imageupload_image_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedImage',
        ),
    ]
